### PR TITLE
Advent24 day1

### PR DESCRIPTION
**Pull request by rianrietveld**
Adds the content of the first advent page "A link on a logo in the header, what should the alt-text be?".

@matuzo Please review :-)

### CODE REVIEW

**Comment by rianrietveld** [comment]
Thank you for reviewing my blogpost.

As an accessibility consultant and teacher, this is the way I teach developers how to code the link on the logo in the header.
To double check, I asked another Dutch accessibility expert and he confirmed this is a good way to do it.

Answering your questions:




Yes in this case there are befits.
This is not a case of adding redundant info like image of or photo of, but the fact that this is a logo tells important info.

Not only for blind users, but for all screenreader users.
If you are a visual impaired but not totally blind, you may see the image vaguely.
And with now with the addition of the word logo, you know what the image is.

The site name is required, but the logo gives extra context.



No, it's not.
The name is in the alt text which becomes the accessible name of the link.
Adding extra context to the link is common practice.
Compair this to the notorious "Read more" link.
Adding a sr-only CSS class (or equivalent) on addition text, like 
`<a href="url">Read more<span class="sr-only"> about cute kitten</a>` is common practice.
You see Read more
You hear Read more about cute kitten

In our case: You see the site logo and you hear the site name and the link destination
What is important for the accessible name is that the text starts with the text thatis visible, for voice recognition software.
The whole text should be in the name, but extra information, like the link destination can be added.




No is aria required in this solution.
As for adding a heading: a heading should be followed by related content and just the logo as content seems overkill.
Sighted users know from experience that a logo is a link to the homepage, screen reader users can target the link from the link list of the screen reader.
Adding a heading with an aria-labelledby seems a violation of the [first rule of ARIA](https://www.w3.org/TR/using-aria/#rule1 to me 😉 , here plain simple HTML does the job too.

This is how I teach it and how in the Netherlands we advice to do this, this is accepted by the Dutch audits as valid solutions.

Of course there are other and also valid solutions, but the assignment for this blogpost was: what is you favourite code snippet, and here it is :-)

Hope this helps, if you have more questions please let me know.

**Comment by rianrietveld** [comment]
@matuzo please read the reply in GitHub and not in the mail, I forgot that your comments where also comment out in the reply. I fixt that now.

**Comment by matuzo** [comment]
Thanks for the detailed answers @rianrietveld. Do want to make any changes to address our questions since others may have them too or do you want to leave it as is? I'm cool with both.

**Comment by rianrietveld** [comment]
Hi @matuzo 
I added a PR with a section discussion, answering questions readers may have.
Please feel free to correct spelling or grammar mistakes.
I hope this helps.

**Comment by matuzo** [comment]
Perfect, thank you!

**Pull request merged**
