### PR TITLE
Adding advent calendar article for day 27

### PR DESCRIPTION
**Pull request by alexmuzenhardt**
Article from Alex Muzenhardt for advent calendar day 27

### CODE REVIEW

**Comment by alexmuzenhardt** [comment]
@matuzo FYI

**Comment by matuzo** [comment]
Hey Alex,

thanks a lot for your great post. I've added some comments directly in your file in the advent24 branch of the HTMHell repository. Sorry that we're not using GitHub and its comment feature as intended but our approach makes it easier for us since not all authors are using GitHub.

Please review my comments, make your changes if necessary, and submit another PR. Your post goes online in 10 days. It would be great if you could submit your changes a couple of days earlier. If you have questions please ask them here.

Thanks a lot,
Manuel

**Comment by alexmuzenhardt** [comment]
Hi Manuel,

thanks. I will check your comments and create a new PR with my changes until Sunday.

Cheers
Alex

**Comment by alexmuzenhardt** [comment]
@matuzo I have read your comments and your mentioned articles. Great ones and I totally agree with them. 

- I will change my article, so that the alternative approach will be the one with aria-label
- I will add a new section to my article called something like "What to use" and describe why we should not use the aria-label approach although it is less code.
- I will remove the screenshots as you wanted

The changes will be done today. I will create a new PR, so that you can review it the next two days.

Cheers
Alex

**Comment by matuzo** [comment]
Perfect, thank you!

**Pull request merged**
