### PR TITLE
Added toggle for dark mode, css variables for background & text color…

### PR DESCRIPTION
**Pull request by joeczar**
Hi, I thought I'd give the dark mode toggle a try. It looks like I reformatted your base.njk. It wasn't my intention.

I went through and added CSS variables to the backgrounds and fonts that changed in style.css and prism.css.

I pulled the javascript from here: [darrk/light switch](https://dev.to/ananyaneogi/create-a-dark-light-mode-switch-with-css-variables-34l8 ) and added an attribution link comment in the file.

I love the site! This is my first pull request and I jumped on it because I love the satanic twist  (I'm a bit of a metalhead). I'd love to help out more if this goes well. Und, ich kann auch Deutsch falls dass hilft.

Thanks for the awesome site, and keep it up!
Grüße aus Berlin,
Joe

### CODE REVIEW

**Comment by joeczar** [comment]
Breaks in ie11

**Comment by matuzo** [comment]
Hi Joe,

I’m sorry that it took me so long to reply. I saw that you’ve noticed that people are already working on the toggle. This doesn’t mean that you can’t contribute. It’d be great if you’d still join us in bringing this feature to live. :)
You’ve closed the PR, but since this is your first, here’s some feedback anyway:

- The reformatting makes the file hard to read. If you notice that, don’t push it, but fix it locally and then only push the changes.
- There’s a yarn.lock and style-old.css file that wasn’t there before. Please avoid pushing stuff that doesn't belong.
- Avoid overly specific selectors like `.slider.round:before`. We use the BEM syntax, so something like `.slider--round` or just applying the styles directly to `.slider` would be preferred.

Würde mich freuen, wenn du weiterhin etwas zum Projekt beiträgst. Es gibt immer wieder was. :)

Thanks for your contribution,
Manuel

**Comment by joeczar** [comment]
Hi Manuel,
Vielen Dank für dein Feedback! Ich habe es extra notiert. I'm looking forward to helping out with this more but I've started a bootcamp here in Berlin and it's taking up most of my time. But I'm learning a lot and am excited to be able to use it.

Wir mussten ein "Ticker" bauen und ich habe mich inspirieren lassen von htmHell. Die obere ticker is nur links von deine seite. 
image


Beste Grüße,
Joe

**Comment by matuzo** [comment]
Yeah, sehr cool! :)

Viel Erfolg mit dem Bootcamp.

**Pull request closed without merging**
